// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmYnSBeDIv7nVmWbAo_pptgzol5SEL4nM',
    appId: '1:186239521512:web:612e473b63364fd5572f5d',
    messagingSenderId: '186239521512',
    projectId: 'fashion-tech-2fdb3',
    authDomain: 'fashion-tech-2fdb3.firebaseapp.com',
    storageBucket: 'fashion-tech-2fdb3.firebasestorage.app',
    measurementId: 'G-2JGRVM6KZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMfNhkeOnO2un3nIpsgg9MyEtv-GbuHgk',
    appId: '1:186239521512:android:ebb19f90674ce0ab572f5d',
    messagingSenderId: '186239521512',
    projectId: 'fashion-tech-2fdb3',
    storageBucket: 'fashion-tech-2fdb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjz8cBzjtB88B0vywoRSuCyCN1Lxrl4zc',
    appId: '1:186239521512:ios:5631313a1ed3f9f4572f5d',
    messagingSenderId: '186239521512',
    projectId: 'fashion-tech-2fdb3',
    storageBucket: 'fashion-tech-2fdb3.firebasestorage.app',
    iosBundleId: 'com.example.fashionTech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjz8cBzjtB88B0vywoRSuCyCN1Lxrl4zc',
    appId: '1:186239521512:ios:5631313a1ed3f9f4572f5d',
    messagingSenderId: '186239521512',
    projectId: 'fashion-tech-2fdb3',
    storageBucket: 'fashion-tech-2fdb3.firebasestorage.app',
    iosBundleId: 'com.example.fashionTech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmYnSBeDIv7nVmWbAo_pptgzol5SEL4nM',
    appId: '1:186239521512:web:1f34127128266571572f5d',
    messagingSenderId: '186239521512',
    projectId: 'fashion-tech-2fdb3',
    authDomain: 'fashion-tech-2fdb3.firebaseapp.com',
    storageBucket: 'fashion-tech-2fdb3.firebasestorage.app',
    measurementId: 'G-VKRTKCH5N0',
  );
}
